# Generated by Django 5.1.6 on 2025-03-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Unknown Brand', max_length=100)),
                ('model', models.CharField(default='Unknown Model', max_length=100)),
                ('size', models.CharField(default='M', max_length=10)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('helmet_type', models.CharField(choices=[('Full Face', 'Full Face'), ('Half Face', 'Half Face'), ('Modular', 'Modular'), ('Off-Road', 'Off-Road'), ('Open Face', 'Open Face')], default='Full Face', max_length=20)),
                ('visor_type', models.CharField(choices=[('Single Visor', 'Single Visor'), ('Double Visor', 'Double Visor')], default='Single Visor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RestockLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('restock_date', models.DateTimeField(auto_now_add=True)),
                ('added_quantity', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etms_app.helmet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etms_app.helmet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
