# Generated by Django 5.1.6 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmet',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
