# Generated by Django 5.1.6 on 2025-03-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0002_alter_helmet_brand_alter_helmet_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='helmet',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='RestockLog',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
